language: c
dist: trusty
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-10
install: make get-deps
script:
  - sudo ln -s /usr/bin/gcc-10 /usr/local/bin/gcc
  - gcc --version
  - make
  - make test
